[package]
name = "truenas_client"
version = "0.1.0"
edition = "2021"
authors = ["Confused Engineer"]

[dependencies]
davids-awesome-library = {path = "../davids-awesome-library"}
truenas_lib = {path = "./truenas_lib"}
prometheus_lib = {path = "./prometheus_lib"}
simple_crypt = "0.2.3"


